project:
  output-dir: docs

lang: pt-BR

format: 
  clean-revealjs:
  # revealjs:
    theme: [default, custom.scss]
    # self-contained: true
    incremental: true
    # smaller: true
    logo: imagens/logo_UFLA.png
    auto-stretch: false
    #chalkboard: true

author:
  name: Prof. Luiz Merschmann
  affiliation: Departamento de Computação Aplicada - UFLA
  url: https://luiz.dac.ufla.br


#title-block-banner: true

date: last-modified
date-format: "DD/MM/YYYY"