project:
  output-dir: docs

lang: pt-BR

format: 
  clean-revealjs: #plugin que tive que instalar para usar um tema "clean"
    theme: [default, custom.scss]
    #theme: [default]
    # self-contained: true
    incremental: true
    # smaller: true
    logo: imagens/logo_UFLA.png
    auto-stretch: false
    #chalkboard: true

revealjs-plugins:
  - pointer # Plugin instalado para permitir mudar o ponteiro durante a apresentacao (tecla q)

author:
  name: Prof. Luiz Merschmann
  affiliation: Departamento de Computação Aplicada - UFLA
  url: https://luiz.dac.ufla.br


title-block-banner: true

date: last-modified
date-format: "DD/MM/YYYY"

filters:
  #- roughnotation
  - code-fullscreen

highlight-style: github